final touch ns

diff --git a/ns b/ns
--- a/ns
+++ b/ns
@@ -1,11 +1,13 @@
 #!/bin/bash
-# Contributor: https://github.com/mdwajid095/ns
+# Repo: https://github.com/mdwajid095/ns
 
 # Define some colors for better visibility
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-BLUE='\033[0;34m'
-NC='\033[0m' # No Color
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+YELLOW=$(tput setaf 3)
+BLUE=$(tput setaf 4)
+CYAN=$(tput setaf 6)
+NC=$(tput sgr0)  # No Color
 
 [[ -n $DEBUG ]] && set -x
 set -eou pipefail
@@ -23,6 +25,9 @@ show_help() {
            $SELF                    : Set namespace across multiple cluster
            $SELF <NAME>             : Set namespace within cluster
            $SELF -c,--current       : Show current namespace
+	   $SELF -a,--all           : List all namespaces
+	   $SELF -x,--history       : Show the history of namespaces changed
+	   $SELF -,-b,--back,.      : Switch back to the previous namespace
            $SELF -h,--help          : Show help
 
 EOF
@@ -37,6 +42,11 @@ list_clusters() {
 # Function to list namespaces
 list_namespaces() {
     local cluster=$1
+
+	if [ "${cluster}" == "-a" ] || [ "${cluster}" == "--all" ]; then
+        cluster=$(kubectl config current-context)
+    fi
+
     kubectl config use-context "${cluster}"
     echo -e "${BLUE}Namespaces in ${cluster}:${NC}"
     kubectl get namespaces -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | cat -n
@@ -48,22 +58,36 @@ set_namespace() {
     local cluster=$1
     local namespace=$2
 
+	# Check if the namespace exists in the cluster
+    if ! kubectl get namespace "${namespace}" > /dev/null 2>&1; then
+        echo -e "${RED}Provided namespace does not exist in the cluster '${cluster}'${NC}"
+		print_instruction
+        return 1
+    fi
+
     kubectl config use-context "${cluster}"
     kubectl config set-context --current --namespace="${namespace}"
 
-    echo -e "${RED}Namespace has been set to '${namespace}' in ${cluster}${NC}"
+    echo -e "${GREEN}Namespace has been set to '${namespace}' in ${cluster}${NC}"
+	echo "${cluster}:${namespace}" >> ~/.namespace_history
+	tail -n 10 ~/.namespace_history > temp_file && mv temp_file ~/.namespace_history
 }
 
 # Function to set namespace within cluster
 set_ns() {
     local namespace=$1
+	local cluster
 
     if kubectl get namespace "${namespace}" > /dev/null 2>&1; then
         kubectl config set-context --current --namespace="${namespace}"
         echo -e "${GREEN}Namespace has been set to '${namespace}'${NC}"
     else
-        echo -e "${RED}No such namespace '${namespace}' in this cluster.${NC}"
+        echo -e "${RED}No such namespace '${namespace}' in this cluster${NC}"
+        print_instruction
     fi
+	cluster=$(kubectl config current-context)
+	echo "${cluster}:${namespace}" >> ~/.namespace_history
+	tail -n 10 ~/.namespace_history > temp_file && mv temp_file ~/.namespace_history
 }
 
 # Function to show current namespace
@@ -72,10 +96,30 @@ show_current_namespace() {
     echo -e "${GREEN}Current namespace is ${current_ns} ${NC}"
 }
 
+# Function to switch back to previous ns
+switch_back() {
+    local last_namespace
+	last_namespace=$(tail -n 2 ~/.namespace_history | head -n 1)
+    local cluster=${last_namespace%:*}
+    local namespace=${last_namespace#*:}
+
+    set_namespace "${cluster}" "${namespace}"
+}
+
+show_namespace_history() {
+    echo -e "${CYAN}Cluster Name\t\tNamespace${NC}"
+    awk -F: '{print $1 "\t" $2}' ~/.namespace_history
+}
+
+print_instruction(){
+echo -e "${YELLOW}Execute for help: ns -h ${NC}"
+}
+
 # Check if the input is a number
 if_number(){
   if ! [[ $1 =~ ^[0-9]+$ ]]; then
-    echo "Error: Input must be a number."
+    echo -e "${RED}Error: Input must be a number${NC}"
+    print_instruction
     exit 1
   fi
 }
@@ -95,7 +139,8 @@ if [[ -z "${KUBECTL:-}" ]]; then
 fi
 
 if (( "$#" > 1 )); then
-  echo "Error: More than one flag provided" >&2
+  echo -e "${RED}Error: More than one flag provided${NC}" >&2
+  print_instruction
   exit 1
 fi
 
@@ -105,16 +150,25 @@ while (( "$#" )); do
       show_current_namespace
       exit 1
       ;;
+	-a|--all)
+      list_namespaces "$1"
+      exit 1
+      ;;
+	-|-b|--back|.)
+      switch_back
+      exit 1
+      ;;
+	-x|--history)
+      show_namespace_history
+      exit 1
+      ;;
     -h|--help)
       show_help
       exit 1
       ;;
-    -|.) # end argument parsing
-      shift
-      break
-      ;;
     -*|.*) # unsupported flags
-      echo "Error: Unsupported flag $1" >&2
+      echo -e "${RED}Error: Unsupported flag $1 ${NC}" >&2
+      print_instruction
       exit 1
       ;;
         *)
@@ -126,13 +180,13 @@ done
 
 if (( "$#" == 0 )); then
   list_clusters
-  read -rp "Enter the number of the cluster to be set: " cluster_number
+  read -rp "${CYAN}Enter the number of the cluster to be set: ${NC}" cluster_number
   cluster_number=${cluster_number:-1}
   if_number "${cluster_number}"
   cluster=$(kubectl config get-contexts -o name | sed -n "${cluster_number}p")
 
   list_namespaces "${cluster}"
-  read -rp "Enter the number of the namespace to be set: " namespace_number
+  read -rp "${CYAN}Enter the number of the namespace to be set: ${NC}" namespace_number
   namespace_number=${namespace_number:-1}
   if_number "${namespace_number}"
   namespace=$(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | sed -n "${namespace_number}p")
